# Name of the speller package in various languages.
# The default is English + autonym:
[speller.name]
en = "Meänkieli (Tornedalen Finnish spellchecker"
fit = "Autonym spellchecker"

# Description of the speller package in various languages.
# The default is English + autonym:
[speller.description]
en = "A spellchecker for Meänkieli (Tornedalen Finnish, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"
fit = "TRANSLATE: A spellchecker for Meänkieli (Tornedalen Finnish, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"

[macos]
system_pkg_id = "no.divvun.MacDivvun.fit"

[windows]
system_product_code = "{77575EA4-966E-4F26-B956-06FC1CE3C3D6}_is1"
legacy_product_codes = [
    { value = "47877A58-DF15-40AF-ABB4-C6C2CE41EE2D", kind = "nsis" },
    { value = "8F506290-ECCD-484E-B335-63DFDB31245D", kind = "nsis" }
]
extra_locales = { fit-SE = "fit" }

[package.speller]
name = "Meänkieli (Tornedalen Finnish"
version = "0.1.1"

[package.grammar]
name = "Meänkieli (Tornedalen Finnish"
version = "0.1.0"

[package.tts-text-proc]
name = "Meänkieli (Tornedalen Finnish"
version = "0.1.0"
