template = "https://github.com/giellalt/template-lang-und"
rev_id = 259
template_sha = "dbafdbc00bdeb17f80ec54b2fd5d6ae330f25f51"

[replacements]
__GLOTTOLOG_ID__ = "torn1244"
__REPO__ = "lang-fit"
__UND2C__ = "fit"
__UNDEFINED__ = "Tornedalen Finnish"
__UND__ = "fit"
