template = "https://github.com/giellalt/template-lang-und"
rev_id = 262
template_sha = "e76bfc45ca43118d648ca429564512658ac2ea78"

[replacements]
__GLOTTOLOG_ID__ = "torn1244"
__REPO__ = "lang-fit"
__UND2C__ = "fit"
__UNDEFINED__ = "Tornedalen Finnish"
__UND__ = "fit"
